config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "corporations#index"

  resources :corporations do
    get 'donnees/find_by_year', to: 'donnees#find_by_year', as: 'find_donnee_by_year'
    post 'corporations/save_year', to: 'corporations#save_year', as: 'save_year_corporations'
    post 'import', on: :collection
    resources :donnees, only: [:edit]
    resources :adherents do
      get :new_avec_adherent, on: :collection
      post :create_avec_adherent, on: :collection
      resources :formulaires, only: [:edit, :update, :show, :new, :create, :destroy] do
        get 'download', on: :member
      end
    end
  end
end

app/models/corporation.rb
class Corporation < ApplicationRecord
  has_many :adherents
  has_many :donnees
end

app/controllers/corporations_controller.rb
class CorporationsController < ApplicationController
  require 'csv'

  def index
    @corporations = Corporation.all
    @corporations = Corporation.includes(:donnees)
    @annees = Annee.all
    @latest_donnees = {}
    @corporations.each do |corporation|
      @latest_donnees[corporation.id] = corporation.donnees.order(annee: :desc).first
    end
    @corporations = Corporation.includes(:adherents)
  end

  def show
    @corporation = Corporation.find(params[:id])
    @q = @corporation.adherents.ransack(params[:q])
    @selected_year = params[:selected_year] || Time.now.year
    session[:selected_year] = @selected_year

    if params[:show_all_adherents] == "1"
      @adherents = @q.result(distinct: true).includes(:formulaires)
    else
      @adherents = @q.result(distinct: true).includes(:formulaires).select do |adherent|
        adherent.formulaires.any? { |formulaire| formulaire.annee == @selected_year }
      end
    end

    @adherent_years = {}
    @adherents.each do |adherent|
      @adherent_years[adherent.id] = adherent.formulaires.pluck(:annee).uniq.sort.reverse
    end
  end


  def edit
    @corporation = Corporation.find(params[:id])
    @selected_year = params[:selected_year] || Time.now.year
    session[:selected_year] = @selected_year
    @donnees = @corporation.donnees.where(annee: params[:selected_year])
  end

  def select_year
    selected_year = params[:selected_year]
    session[:selected_year] = selected_year
    redirect_back fallback_location: corporations_path
  end

  def update
    @corporation = Corporation.find(params[:id])
    if @corporation.update(corporation_params)
      redirect_to root_path, notice: 'Corporation mise à jour avec succès.'
    else
      flash.now[:alert] = 'Erreur lors de la mise à jour de la corporation.'
      render :edit
    end
  end

  def nettoyer_chaine(chaine)
    return chaine if chaine.nil?
    chaine.gsub!(/\p{Cntrl}/, '')
    chaine.strip!
    chaine
  end

  def import
    file = params[:file].tempfile
    options = { headers: true, col_sep: ';' }

    CSV.foreach(file, **options) do |row|
      user_hash = {}
      user_hash[:nom_prenom] = row['Nom']
      user_hash[:email] = row['E-mail']
      user_hash[:raison_sociale] = row['Raison Sociale']
      user_hash[:adresse] = row['Adresse']
      user_hash[:cp_ville] = "#{row['Code Postal']} #{row['Commune']}"
      user_hash[:portable] = row['Numéro Téléphone Portable']
      user_hash[:telephone] = row['Numéro Téléphone']
      user_hash[:siret] = row['N° SIRET']
      user_hash[:annee] = row['année']
      user_hash[:forme_juridique] = row ['Forme Juridique']

      existing_adherent = Adherent.find_by(nom: row['Nom'], corporation_id: row['Corporation'])

      if existing_adherent
        formulaire = Formulaire.new(user_hash.merge(adherent_id: existing_adherent.id))
        existing_formulaire = existing_adherent.formulaires.where(annee: row['année'])
        if existing_formulaire.empty?
          if formulaire.save
            puts "Formulaire sauvegardé avec succès pour l'adhérent existant : #{existing_adherent.id}"
          else
            puts "Erreur lors de la sauvegarde du formulaire pour l'adhérent existant"
          end
        else
          puts "Le formulaire pour l'adhérent existant existe déjà"
        end

      else
        puts "Aucun adhérent avec le même nom et la même corporation n'existe pas"
        nouvel_adherent = Adherent.new(nom: row['Nom'], corporation_id: row['Corporation'])

        if nouvel_adherent.save
          puts "Nouvel adhérent créé avec succès : #{nouvel_adherent.id}"
          formulaire = Formulaire.new(user_hash.merge(adherent_id: nouvel_adherent.id))

          if formulaire.save
            puts "Formulaire sauvegardé avec succès pour le nouvel adhérent : #{nouvel_adherent.id}"
          else
            puts "Erreur lors de la sauvegarde du formulaire pour le nouvel adhérent"
          end
        else
          puts "Erreur lors de la création du nouvel adhérent"
        end
      end
    end
    redirect_to root_path, notice: "Les données ont été importées avec succès."
  end


  private

  def corporation_params
    params.require(:corporation).permit(:nom)
  end

end

app/views/corporations/edit.html.erb
<div class="container mx-auto px-4">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-3xl font-bold">Modifier le nom de la corporation</h1>
    <%= link_to "Retour", request.referer, class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4" %>
  </div>

  <% @donnees.each do |donnee| %>

    <%= form_with(:model => @corporation, :data   => { turbo: true, turbo_confirm: "Are you Sure?" } ,local: true) do |form| %>
      <div class="mb-4">
        <%= form.label :nom, "Nom actuel : #{@corporation.nom}", class: "block text-gray-700 text-sm font-bold mb-4" %>
        <%= form.text_field :nom, class: "form-input w-full mb-4" %>
        <%= donnee.adresse %>
      </div>
      <div class="flex justify-end">
        <%= form.submit "Enregistrer", data: { confirm: "Are you sure?" }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/corporations/index.html.erb
<%= stylesheet_link_tag "corporation" %>
<%= javascript_include_tag "index_corporations", type: :module %>

<div class="container mx-auto px-4">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-3xl font-bold">Corporations</h1>

    <div class="flex items-center">
      <p class="mr-4">Exercice en cours:</p>
      <%#= select_tag :selected_year, options_for_select(Annee.all.map(&:annee), selected: Time.now.year), onchange: "updateLink(this)", id: "selected_year", class: "border border-gray-300 rounded-lg px-3 py-2 pr-8 focus:outline-none" %>
      <%= select_tag :selected_year, options_for_select(Annee.all.map(&:annee), selected: Time.now.year), onchange: "updateShowButton(this)", class: "border border-gray-300 rounded-lg px-3 py-2 pr-8 focus:outline-none" %>
    </div>
  </div>

  <%= form_with url:  import_corporations_path(@corporation), multipart: true, method: :post, class: "flex flex-row" do |form| %>
    <div class="flex flex-row items-center mb-2 ">
      <%= form.file_field :file, accept: ".csv" %>
      <%= form.button "Importer ▶️", class: "boutton-importer" %>
    </div>
  <% end %>

  <div class="overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-100 uppercase tracking-wider">Nom Corporation</th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-100 uppercase tracking-wider">
          <div class="mx-auto" style="width: max-content;">
            Nombre d'adhérents
          </div>
        </th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-100 uppercase tracking-wider text-center">Actions</th>
      </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
      <% @corporations.each do |corpo| %>
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">
            <div class="text-sm text-gray-900">
              <% latest_donnee = @latest_donnees[corpo.id] %>
              <% if latest_donnee %>
                <b><%= latest_donnee.nom_formulaire.upcase %></b>
              <% end %>
            </div>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-center">
            <div class="text-sm text-gray-900"><%= corpo.adherents.count %></div>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-center">
            <%= link_to "Voir les adhérents", corporation_path(corpo, selected_year: Time.now.year), data: { turbo: false }, class: "show-button text-blue-500 font-semibold hover:underline" %> |
            <%= link_to "Paramètres", edit_corporation_donnee_path(corpo, @latest_donnees[corpo.id], selected_year: Time.now.year), data: { turbo: false }, id: "edit_link", class: "show-button text-blue-500 font-semibold hover:underline" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/corporations/show.html.erb
<%= stylesheet_link_tag "index" %>
<%= javascript_include_tag "show_corporations", type: :module %>

<div class="container mx-auto px-4">
  <div class="flex flex-col md:flex-row justify-between items-start md:items-center">
    <h1 class="text-3xl font-bold mb-2 md:mb-0">Adhérents</h1>
    <a href="<%= root_path %>" class="button-primary">Retour à l'accueil</a>
  </div>
  <p class="text-sm mb-4">Exercices en cours :  <%= @selected_year %></p>

  <div class="flex mb-4">
    <%= search_form_for @q, url: corporation_path(@corporation), html: { class: "search-form flex-1", id: "combined-form" } do |f| %>
      <div class="flex">
        <%= f.search_field :nom_or_numero_adherent_cont, placeholder: "Rechercher par nom ou numéro adhérent", class: "w-full px-4 py-2 rounded border border-gray-300" %>
        <%= hidden_field_tag :selected_year, @selected_year %>
        <%= check_box_tag "show_all_adherents", 1, params[:show_all_adherents], id: "show_all_adherents", class: "mr-2" %>
        <%= label_tag "show_all_adherents", "Afficher tous les adhérents", class: "pt-2" %>
        <%= f.submit "Rechercher", class: "button-primary ml-2" %>
      </div>
    <% end %>
    <%= link_to "Créer un formulaire avec un nouvel adhérent", new_avec_adherent_corporation_adherents_path(@corporation), data: { turbo: false }, class: "button-primary ml-2" %>
  </div>

  <table class="min-w-full divide-y divide-gray-200">
    <thead>
    <tr>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-2/5">Nom</th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/5">Année</th>
      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-2/5">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @adherents.each do |adherent| %>
      <tr class="bg-white">
        <td class="px-6 py-4 whitespace-nowrap w-2/5"><%= adherent.nom.capitalize %></td>
        <td class="px-6 py-4 whitespace-nowrap w-1/5">
          <%= form_tag(corporation_adherent_formulaire_path(@corporation, adherent, annee: ""), method: "get", class: "flex flex-wrap justify-between") do %>
            <div>
              <%= select_tag "annee", options_for_select(@adherent_years[adherent.id]), class: "form-select rounded-md", id: "year-select-#{adherent.id}", onchange: "updateYearSelect(this)" %>
            </div>
        </td>
        <td class="px-6 py-4 whitespace-nowrap w-2/5">
            <div class="flex">
              <%= submit_tag "Voir", name: "voir", class: "button-primary mr-2" %>
              <% if @adherent_years[adherent.id].include?(params[:selected_year]) %>
                <%= link_to "Créer un formulaire", "#", class: "button-disabled mr-2", data: { disable_with: "Processing...", tooltip: "Ce bouton est actuellement désactivé" } %>
              <% else %>
                <%= link_to "Créer un formulaire", new_corporation_adherent_formulaire_path(@corporation, adherent), class: "button-primary mr-2" %>
              <% end %>
              <%= link_to 'Télécharger PDF', corporation_adherent_formulaire_path(@corporation, adherent, annee: @selected_year, telecharger: true), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 ml-2 rounded', id: 'download-link' %>
            </div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="3" class="h-px gradient-line"></td>
      </tr>
    <% end %>
    </tbody>
  </table>


</div>