config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "corporations#index"

  resources :corporations do
    get 'donnees/find_by_year', to: 'donnees#find_by_year', as: 'find_donnee_by_year'
    post 'corporations/save_year', to: 'corporations#save_year', as: 'save_year_corporations'
    post 'import', on: :collection
    resources :donnees, only: [:edit]
    resources :adherents do
      get :new_avec_adherent, on: :collection
      post :create_avec_adherent, on: :collection
      resources :formulaires, only: [:edit, :update, :show, :new, :create, :destroy] do
        get 'download', on: :member
      end
    end
  end
end

app/models/adherent.rb
class Adherent < ApplicationRecord
  belongs_to :corporation
  has_many :formulaires


  # RANSACK (SEARCHBAR)
  ransacker :numero_adherent_string do
    Arel.sql("to_char(\"#{table_name}\".\"numero_adherent\", '9999999')")
  end

  def self.ransackable_associations(auth_object = nil)
    super
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[corporation_id created_at id id_value nom numero_adherent updated_at]
  end

end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  def new_avec_adherent
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.new(corporation: @corporation)
    @formulaire = @adherent.formulaires.build
    @annee = trouver_annee
    @donnees = Donnee.where(corporation_id: @corporation.id, annee: @annee)
  end

  def create_avec_adherent
    @corporation = Corporation.find(params[:corporation_id])
    @formulaire = Formulaire.new(formulaire_params)
    @adherent = Adherent.new(nom: @formulaire.nom_prenom, corporation: @corporation)
    @formulaire.adherent = @adherent
    @formulaire.annee = session[:selected_year]
    if @adherent.save && @formulaire.save
      redirect_to corporation_path(@corporation, selected_year: session[:selected_year]), notice: 'Adherent and Formulaire were successfully created.'
    else
      render :new_avec_adherent
    end
  end

  def edit
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.find(params[:id])
  end

  def update
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.find(params[:id])

    if @adherent.update(adherent_params)
      redirect_to corporation_path(@corporation), notice: 'Les informations de l\'adhérent ont été mises à jour avec succès.'
    else
      render :edit
    end
  end

  def trouver_annee
    current_year = session[:selected_year]
    donnee = Donnee.find_by(corporation_id: @corporation.id, annee: current_year)
    if donnee
      return donnee.annee
    else
      return Donnee.where(corporation_id: @corporation.id).where("annee < ?", current_year).order(annee: :desc).pluck(:annee).first
    end
  end

  private

  def adherent_params
    params.require(:adherent).permit(:nom)
  end

  def formulaire_params
    params.require(:formulaire).permit(:raison_sociale, :nom_prenom, :adresse, :cp_ville, :telephone, :portable, :email, :statut, :forme_juridique, :siret, :nb_salaries, :nb_apprentis, :mode_paiement, :lieu, :date, :titulaire_compte, :adresse_sepa, :cp_ville_sepa, :iban_sepa, :bic_sepa, :lieu_date_sepa, :annee, :checkbox_1, :code_naf_ape, :checkbox_2,  :checkbox_3, :checkbox_4, :checkbox_5, :champ_1, :champ_2, :champ_3, :champ_4, :champ_5, :checkbox_6)
  end

end


app/views/adherents/edit.html.erb
<div class="container mx-auto px-4">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-3xl font-bold">Modifier le nom de la corporation</h1>
    <%= link_to "Retour", corporation_path(@corporation), data: { turbo: false },  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>

  <%= form_with(model: [@corporation, @adherent], url: corporation_adherent_path(@corporation, @adherent), method: :patch) do |form| %>
    <div class="mb-4">
      <%= form.label :nom, "Nom actuel : #{@adherent.nom}", class: "block text-gray-700 text-sm font-bold mb-4" %>
      <%= form.text_field :nom, class: "form-input w-full mb-4" %>
    </div>
    <div class="flex justify-end">
      <%= form.submit "Enregistrer", data: { confirm: "Are you sure?" }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/adherents/new_avec_adherent.html.erb
<div class="flex flex-col">
  <div class="flex justify-between items-center">
    <%= javascript_include_tag "scroll_down", type: :module %>
    <%= link_to "Retour", corporation_path(@corporation, selected_year: session[:selected_year]), data: { turbo: false }, class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4" %>
    <%= button_tag "Bas de la page", id: "scroll-to-bottom-button", class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4 place-self-start" %>
  </div>

  <% corporation_id = params[:corporation_id] %>

  <% if corporation_id == '1' %>
    <%= render partial: 'peintres' %>
  <% elsif corporation_id == '2'%>
    <%= render partial: 'boulangers' %>
  <% elsif corporation_id == '3'%>
    <%= render partial: 'coiffeurs' %>
  <% elsif corporation_id == '4'%>
    <%= render partial: 'menuisiers' %>
  <% elsif corporation_id == '5'%>
    <%= render partial: 'copama' %>
  <% elsif corporation_id == '6'%>
    <%= render partial: 'estheticiennes' %>
  <% else %>
    <% redirect_to root_path %>
  <% end %>

</div>


