config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "corporations#index"

  resources :corporations do
    get 'donnees/find_by_year', to: 'donnees#find_by_year', as: 'find_donnee_by_year'
    post 'corporations/save_year', to: 'corporations#save_year', as: 'save_year_corporations'
    post 'import', on: :collection
    resources :donnees, only: [:edit]
    resources :adherents do
      get :new_avec_adherent, on: :collection
      post :create_avec_adherent, on: :collection
      resources :formulaires, only: [:edit, :update, :show, :new, :create, :destroy] do
        get 'download', on: :member
      end
    end
  end
end

app/models/formulaire.rb
class Formulaire < ApplicationRecord
  belongs_to :adherent
end

app/controllers/formulaires_controller.rb
class FormulairesController < ApplicationController

  #before_action :set_formulaire, only: [:edit, :update]
  def show
    @corporation = Corporation.find(params[:corporation_id])
    @selected_year = session[:selected_year]
    @adherent = Adherent.find(params[:adherent_id])
    @annee = params[:annee]
    @formulaire = @adherent.formulaires.find_by(annee: @annee)
    @donnees = Donnee.where(corporation_id: @corporation.id).where("annee <= ?", @annee).order(annee: :desc).first
    @show_mode = true
    if params[:telecharger] == "true"
      html = render_to_string(template: "formulaires/show", formats: [:html])
      grover = Grover.new(html,
                          scale: 0.40,
                          encoding: 'utf8',
                          style_tag_options: [{ path: "app/assets/stylesheets/corporation.css" }],
                          puppeteer: {
                            args: ["--no-sandbox"]
                          })
      pdf = grover.to_pdf
      send_data(
        pdf,
        filename: "formulaire_#{params[:annee]}.pdf",
        type: "application/pdf",
        disposition: "attachment"
      )
    end
  end
  
  def new
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.find(params[:adherent_id])
    @selected_year = session[:selected_year]
    all_data = @corporation.donnees
    @donnees = all_data.find_by(annee: @selected_year) || all_data.where('annee < ?', @selected_year).order(annee: :desc).first
    @formulaire = Formulaire.new
    @formulaire.annee = @selected_year

  end

  def create
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.find(params[:adherent_id])
    @selected_year = session[:selected_year]
    @formulaire.annee = @selected_year
    @formulaire = @adherent.formulaires.build(formulaire_params)
    if @formulaire.save
      redirect_to @corporation, notice: "Formulaire créé avec succès"
    else
      render :new
    end
  end

  def edit
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.find(params[:adherent_id])
    @formulaire = Formulaire.find(params[:id])
    @annee = @formulaire.annee
    @donnees = Donnee.where(corporation_id: @corporation.id).where("annee <= ?", @annee).order(annee: :desc).first
    #if @donnees.nil?
    #  @donnees = Donnee.where("corporation_id = ? AND annee < ?", @corporation.id, @formulaire.annee).order(annee: :desc).first
    #end
  end

  def update
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = @corporation.adherents.find(params[:adherent_id])
    @formulaire = Formulaire.find(params[:id])
    @selected_year = session[:selected_year]
    if @formulaire.update(formulaire_params)
      redirect_to corporation_path(@corporation, selected_year: session[:selected_year]), notice: "Formulaire modifié avec succès"
    else
      render :edit
    end
  end

  def destroy
    @corporation = Corporation.find(params[:corporation_id])
    @adherent = Adherent.find(params[:adherent_id])
    @formulaire = Formulaire.find(params[:id])

    if @formulaire.destroy
      redirect_to corporation_adherent_formulaire_path(@corporation, @adherent), notice: 'Le formulaire a été supprimé avec succès.'
    else
      redirect_to corporation_adherent_formulaire_path(@corporation, @adherent), alert: 'Une erreur est survenue lors de la suppression du formulaire.'
    end
  end

  def set_formulaire
    @formulaire = Formulaire.find(params[:id])
  end

  private

  def formulaire_params
    params.require(:formulaire).permit(:raison_sociale, :nom_prenom, :adresse, :cp_ville, :telephone, :portable, :email, :statut, :forme_juridique, :siret, :nb_salaries, :nb_apprentis, :mode_paiement, :lieu, :date, :titulaire_compte, :adresse_sepa, :cp_ville_sepa, :iban_sepa, :bic_sepa, :lieu_date_sepa, :annee, :checkbox_1, :code_naf_ape,  :checkbox_2,  :checkbox_3, :checkbox_4, :checkbox_5, :champ_1, :champ_2, :champ3, :checkbox_6)
  end

end


app/views/formulaires/edit.html.erb
<div class="flex flex-col">
  <div class="flex justify-between items-center">
    <%= link_to "Retour", request.referer, class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4", data: { turbo: false } %>
    <%= button_tag "Bas de la page", class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4 place-self-start", data: { controller: "scroll-down", action: "click->scroll-down#scrollDown", target: "scroll-down.button"  } %>
  </div>

  <% corporation_id = params[:corporation_id] %>


  <% if corporation_id == '1' %>
    <%= render partial: 'formulaires_edition_show/peintres' %>
  <% elsif corporation_id == '2'%>
    <%= render partial: 'formulaires_edition_show/boulangers' %>
  <% elsif corporation_id == '3'%>
    <%= render partial: 'formulaires_edition_show/coiffeurs' %>
  <% elsif corporation_id == '4'%>
    <%= render partial: 'formulaires_edition_show/menuisiers' %>
  <% elsif corporation_id == '5'%>
    <%= render partial: 'formulaires_edition_show/copama' %>
  <% elsif corporation_id == '5'%>
    <%= render partial: 'formulaires_edition_show/estheticiennes' %>
  <% else %>
    <% redirect_to root_path %>
  <% end %>
</div>






app/views/formulaires/new.html.erb
<div class="flex flex-col">
  <div class="flex justify-between items-center">
    <%= javascript_include_tag "scroll_down", type: :module %>
    <%= link_to "Retour", corporation_path(@corporation, selected_year: session[:selected_year]), data: { turbo: false }, class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4" %>
    <%= button_tag "Bas de la page", id: "scroll-to-bottom-button", class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4 place-self-start" %>
  </div>


  <% corporation_id = params[:corporation_id] %>


  <% if corporation_id == '1' %>
    <%= render partial: 'formulaires_creation/peintres' %>
  <% elsif corporation_id == '2'%>
    <%= render partial: 'formulaires_creation/boulangers' %>
  <% elsif corporation_id == '3'%>
    <%= render partial: 'formulaires_creation/coiffeurs' %>
  <% elsif corporation_id == '4'%>
    <%= render partial: 'formulaires_creation/menuisiers' %>
  <% elsif corporation_id == '5'%>
    <%= render partial: 'formulaires_creation/copama' %>
  <% elsif corporation_id == '5'%>
    <%= render partial: 'formulaires_creation/estheticiennes' %>
  <% else %>
      <% redirect_to root_path %>
  <% end %>

</div>

app/views/formulaires/show.html.erb
<div class="flex flex-col">
  <div class="flex justify-between items-center">
    <%= stylesheet_link_tag "corporation.css" %>
    <%= link_to "Retour", corporation_path(@corporation, selected_year: session[:selected_year]), data: { turbo: false }, class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4" %>
    <%= link_to "Modifier", edit_corporation_adherent_formulaire_path(@corporation, @adherent, @formulaire), data: { turbo: false }, class: "bg-blue-500 text-white font-bold py-2 px-4 rounded mb-4 place-self-start" %>
  </div>

  <meta name="viewport" content="width=device-width,initial-scale=1" charset = "utf-8">


  <% corporation_id = params[:corporation_id] %>


  <% if corporation_id == '1' %>
    <%= render partial: 'formulaires_edition_show/peintres' %>
  <% elsif corporation_id == '2'%>
    <%= render partial: 'formulaires_edition_show/boulangers' %>
  <% elsif corporation_id == '3'%>
    <%= render partial: 'formulaires_edition_show/coiffeurs' %>
  <% elsif corporation_id == '4'%>
    <%= render partial: 'formulaires_edition_show/menuisiers' %>
  <% elsif corporation_id == '5'%>
    <%= render partial: 'formulaires_edition_show/copama' %>
  <% elsif corporation_id == '6'%>
    <%= render partial: 'formulaires_edition_show/estheticiennes' %>
  <% else %>
    <% redirect_to root_path %>
  <% end %>
</div>
